# HW10: Algorithmic Fairness 

### Note: to complete most of this homework notions from week 11 slides are needed

In this homework you will assess racial bias in the COMPAS algorithm and judges decisions. 

The data is a collection of 7000 criminal cases in Florida in which COMPAS was used and it contains information about defendants' demographics, criminal history (e.g., juvenile criminal records), court decision and recidivism.

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings = lambda *a, **kw: None

## Data Preparation

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv')
df.head()

id                name   first         last compas_screening_date   sex  \
0   1    miguel hernandez  miguel    hernandez            2013-08-14  Male   
1   3         kevon dixon   kevon        dixon            2013-01-27  Male   
2   4            ed philo      ed        philo            2013-04-14  Male   
3   5         marcu brown   marcu        brown            2013-01-13  Male   
4   6  bouthy pierrelouis  bouthy  pierrelouis            2013-03-26  Male   

          dob  age          age_cat              race  ...  v_decile_score  \
0  1947-04-18   69  Greater than 45             Other  ...               1   
1  1982-01-22   34          25 - 45  African-American  ...               1   
2  1991-05-14   24     Less than 25  African-American  ...               3   
3  1993-01-21   23     Less than 25  African-American  ...               6   
4  1973-01-22   43          25 - 45             Other  ...               1   

   v_score_text  v_screening_date  in_custody  out_custody  priors_count.1  \
0           Low        2013-08-14  2014-07-07   2014-07-14               0   
1           Low        2013-01-27  2013-01-26   2013-02-05               0   
2           Low        2013-04-14  2013-06-16   2013-06-16               4   
3        Medium        2013-01-13         NaN          NaN               1   
4           Low        2013-03-26         NaN          NaN               2   

  start   end event two_year_recid  
0     0   327     0              0  
1     9   159     1              1  
2     0    63     0              1  
3     0  1174     0              0  
4     0  1102     0              0  

[5 rows x 53 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7214 entries, 0 to 7213
Data columns (total 53 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       7214 non-null   int64  
 1   name                     7214 non-null   object 
 2   first                    7214 non-null   object 
 3   last                     7214 non-null   object 
 4   compas_screening_date    7214 non-null   object 
 5   sex                      7214 non-null   object 
 6   dob                      7214 non-null   object 
 7   age                      7214 non-null   int64  
 8   age_cat                  7214 non-null   object 
 9   race                     7214 non-null   object 
 10  juv_fel_count            7214 non-null   int64  
 11  decile_score             7214 non-null   int64  
 12  juv_misd_count           7214 non-null   int64  
 13  juv_other_count          7214 non-null   int64  
 14  priors_count            

In [4]:
df['days_from_recid'] = pd.to_datetime(df['r_offense_date']) - pd.to_datetime(df['c_offense_date'])
df['days_from_recid'] = df['days_from_recid'].dt.days
df['two_year_recid2'] = (df['days_from_recid']<=730).astype(int)

#generate felony charge dummies
df['felony'] = (df['c_charge_degree'] == 'F').astype(int)

#generate age dummies
d = pd.get_dummies(df['age_cat'])
df = pd.concat([df, d], axis=1)
df = df.rename(columns={'25 - 45':'age_cat_25 - 45', 'Greater than 45':'age_cat_Greater than 45', 'Less than 25':'age_cat_Less than 25'})

#generate ethnicity, race and compas score dummies
d = pd.get_dummies(df['race'])
df = pd.concat([df, d], axis=1)
df['male'] = (df['sex'] == 'Male').astype(int)
d = pd.get_dummies(df['score_text'])
df = pd.concat([df, d], axis=1)
df = df.rename(columns={'High':'score_text_high', 'Medium':'score_text_medium', 'Low':'score_text_low'})

### Setting outcomes and predictors

The *ideal* target variable for the COMPAS algorithm is the presence of a recidivism episode, while for judges is the decision to send the defendant to jail. For the predictors we use some deomgraphic characteristics **excluding race**, criminal hisotry and type of crime. 

In [5]:
# judge decision: "jailed" = more than one day in jail.
df['jail_days'] = pd.to_datetime(df['c_jail_out']) - pd.to_datetime(df['c_jail_in'])
df['jailed'] = (df.jail_days.dt.days > 1).astype(int)
D = df['jailed']
D.value_counts()

0    4283
1    2931
Name: jailed, dtype: int64

In [6]:
# Algorithm outcome
Y = df['two_year_recid2'] 
Y.value_counts()

0    4557
1    2657
Name: two_year_recid2, dtype: int64

In [7]:
# predictors
predictors = ['felony',
              'male', 'age', 
              'juv_fel_count','juv_misd_count', 'juv_other_count', 'priors_count']
X = df[predictors]
X.describe()

felony         male          age  juv_fel_count  juv_misd_count  \
count  7214.000000  7214.000000  7214.000000    7214.000000     7214.000000   
mean      0.646798     0.806626    34.817993       0.067230        0.090934   
std       0.477998     0.394971    11.888922       0.473972        0.485239   
min       0.000000     0.000000    18.000000       0.000000        0.000000   
25%       0.000000     1.000000    25.000000       0.000000        0.000000   
50%       1.000000     1.000000    31.000000       0.000000        0.000000   
75%       1.000000     1.000000    42.000000       0.000000        0.000000   
max       1.000000     1.000000    96.000000      20.000000       13.000000   

       juv_other_count  priors_count  
count      7214.000000   7214.000000  
mean          0.109371      3.472415  
std           0.501586      4.882538  
min           0.000000      0.000000  
25%           0.000000      0.000000  
50%           0.000000      2.000000  
75%           0.000000      5.000000  
max          17.000000     38.000000

In [8]:
df['race'].value_counts()

African-American    3696
Caucasian           2454
Hispanic             637
Other                377
Asian                 32
Native American       18
Name: race, dtype: int64

In [9]:
# indicator variable for non-white
NW = (df['race'] != 'Caucasian').astype(int)
NW.describe()

count    7214.000000
mean        0.659828
std         0.473800
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: race, dtype: float64

## Assessing Algorithm: Predict Recidivism from Features

In the following you will predict recidivism from defendants' features using a nested training/test split so we can get clean test-set predictions for the whole dataset (see the notebook and homework on double machine learning for how to do this - week 6).

In [10]:
# perform nested train/test split 
from sklearn.model_selection import train_test_split
X_a, X_b, Y_a, Y_b, D_a, D_b,NW_a, NW_b = train_test_split(X, Y, D, NW, test_size = 0.5)

df_pred = X_a.append(X_b) 
#TODO train a logit model to predict recidism (Y) from predictors (X).
#TODO form clean test-set predictions for recidivism in the full dataset
from sklearn.linear_model import LogisticRegression
import numpy as np
log_reg = LogisticRegression()
log_reg.fit(X_a, Y_a)
Y_b_pred = pd.DataFrame(log_reg.predict(X_b), index=X_b.index)
log_reg.fit(X_b, Y_b)
Y_a_pred = pd.DataFrame(log_reg.predict(X_a), index=X_a.index)
Y_pred = Y_a_pred.append(Y_b_pred).sort_index()


Evaluate test set performance.

In [11]:
#TODO show a confusion matrix, compute accuracy, balanced accuracy, and roc_auc
#TODO compute ratio of false positives to false negatives

from sklearn.metrics import confusion_matrix, plot_confusion_matrix
from sklearn.metrics import classification_report


display(confusion_matrix(Y, Y_pred))
print(classification_report(Y, Y_pred))


array([[4130,  427],
       [2087,  570]])

              precision    recall  f1-score   support

           0       0.66      0.91      0.77      4557
           1       0.57      0.21      0.31      2657

    accuracy                           0.65      7214
   macro avg       0.62      0.56      0.54      7214
weighted avg       0.63      0.65      0.60      7214



### Compare treatment of whites and non-whites for recidivism prediction
##### Refer to week 11 for these concepts

#### Base Rates

In [12]:
##TODO Compare base rates for recidivism outcomes of whites and non-whites
ydf = pd.DataFrame(Y)
ydf["NW"] = NW
ydf.groupby(NW).mean()

two_year_recid2   NW
race                      
0            0.328036  0.0
1            0.389076  1.0

#### Performance

In [13]:
##TODO Produce confusion matrices, classification reports, and ratio of false positives to false negatives, separately for whites and non-whites.

display(confusion_matrix(Y[NW==0], Y_pred[NW==0]))
print(classification_report(Y[NW==0], Y_pred[NW==0]))

array([[1552,   97],
       [ 698,  107]])

              precision    recall  f1-score   support

           0       0.69      0.94      0.80      1649
           1       0.52      0.13      0.21       805

    accuracy                           0.68      2454
   macro avg       0.61      0.54      0.50      2454
weighted avg       0.64      0.68      0.60      2454



In [14]:
display(confusion_matrix(Y[NW==1], Y_pred[NW==1]))
print(classification_report(Y[NW==1], Y_pred[NW==1]))

array([[2578,  330],
       [1389,  463]])

              precision    recall  f1-score   support

           0       0.65      0.89      0.75      2908
           1       0.58      0.25      0.35      1852

    accuracy                           0.64      4760
   macro avg       0.62      0.57      0.55      4760
weighted avg       0.62      0.64      0.59      4760



**What concepts of "fairness" (from class) are (approximately) satisfied by this classifier? Explain.**

## Assessing Judges' Decisions: Predict Judge Decision from Features

In the following you will predict judges' decisions from defendants' features using a nested training/test split as before. In a second model, include Y-hat from previous section as a predictor.

In [15]:
#TODO train a logit model to predict judge decision (D) from predictors (X). 

log_reg.fit(X_a, D_a)
D_b_pred = pd.DataFrame(log_reg.predict(X_b), index=X_b.index)
D_b_proba = pd.DataFrame(log_reg.predict_proba(X_b), index=X_b.index)
log_reg.fit(X_b, D_b)
D_a_pred = pd.DataFrame(log_reg.predict(X_a), index=X_a.index)
D_a_proba = pd.DataFrame(log_reg.predict_proba(X_a), index=X_a.index)
D_pred = D_a_pred.append(D_b_pred).sort_index()
D_proba = D_a_proba.append(D_b_proba).sort_index()


In [16]:
#TODO train a logit model to predict judge decision (D) from predictors (X) and predicted recidivism risk (Yhat)
#TODO form clean test-set predictions for the decisions in the full dataset

X_a_with_Yhat = X_a.copy()
X_a_with_Yhat["Yhat"] = Y_a_pred
X_b_with_Yhat = X_b.copy()
X_b_with_Yhat["Yhat"] = Y_b_pred

log_reg.fit(X_a_with_Yhat, D_a)
D_b_pred = pd.DataFrame(log_reg.predict(X_b_with_Yhat), index=X_b_with_Yhat.index)
D_b_proba_with = pd.DataFrame(log_reg.predict_proba(X_b_with_Yhat), index=X_b_with_Yhat.index)
log_reg.fit(X_b_with_Yhat, D_b)
D_a_pred = pd.DataFrame(log_reg.predict(X_a_with_Yhat), index=X_a_with_Yhat.index)
D_a_proba_with = pd.DataFrame(log_reg.predict_proba(X_a_with_Yhat), index=X_a_with_Yhat.index)
D_pred_with = D_a_pred.append(D_b_pred).sort_index()
D_proba_with = D_a_proba_with.append(D_b_proba_with).sort_index()

### Compare treatment of whites and non-whites for recidivism prediction

In [17]:
from IPython.display import Markdown, display

def report_inner(true, pred):
    conf_matrix = confusion_matrix(true, pred)
    print("Confusion matrix:")
    display(conf_matrix)
    print("Classificaton report:")
    print(classification_report(true, pred))
    print("Ratio of false positives to false negatives:")
    print(conf_matrix[0,1]/conf_matrix[1,0])

def report_outer(true, pred, group):
    display(Markdown("### Overall:"))
    report_inner(true, pred)
    display(Markdown("### Whites:"))
    report_inner(true[group==0], pred[group==0])
    display(Markdown("### Non-whites:"))
    report_inner(true[group==1], pred[group==1])

def report(true, pred, pred_with):
    display(Markdown("## Without Yhat:"))
    report_outer(true, pred, NW)
    display(Markdown("## With Yhat:"))
    report_outer(true, pred_with, NW)

In [18]:
##TODO Produce confusion matrices, classification reports, and ratio of false positives to false negatives, 
##TODO separately for whites and non-whites, and with/without including Y-hat as a predictor.

report(D, D_pred, D_pred_with)

## Without Yhat:

### Overall:

Confusion matrix:


array([[3777,  506],
       [2221,  710]])

Classificaton report:
              precision    recall  f1-score   support

           0       0.63      0.88      0.73      4283
           1       0.58      0.24      0.34      2931

    accuracy                           0.62      7214
   macro avg       0.61      0.56      0.54      7214
weighted avg       0.61      0.62      0.58      7214

Ratio of false positives to false negatives:
0.22782530391715444


### Whites:

Confusion matrix:


array([[1391,   94],
       [ 800,  169]])

Classificaton report:
              precision    recall  f1-score   support

           0       0.63      0.94      0.76      1485
           1       0.64      0.17      0.27       969

    accuracy                           0.64      2454
   macro avg       0.64      0.56      0.52      2454
weighted avg       0.64      0.64      0.57      2454

Ratio of false positives to false negatives:
0.1175


### Non-whites:

Confusion matrix:


array([[2386,  412],
       [1421,  541]])

Classificaton report:
              precision    recall  f1-score   support

           0       0.63      0.85      0.72      2798
           1       0.57      0.28      0.37      1962

    accuracy                           0.61      4760
   macro avg       0.60      0.56      0.55      4760
weighted avg       0.60      0.61      0.58      4760

Ratio of false positives to false negatives:
0.28993666432090076


## With Yhat:

### Overall:

Confusion matrix:


array([[3766,  517],
       [2200,  731]])

Classificaton report:
              precision    recall  f1-score   support

           0       0.63      0.88      0.73      4283
           1       0.59      0.25      0.35      2931

    accuracy                           0.62      7214
   macro avg       0.61      0.56      0.54      7214
weighted avg       0.61      0.62      0.58      7214

Ratio of false positives to false negatives:
0.235


### Whites:

Confusion matrix:


array([[1381,  104],
       [ 785,  184]])

Classificaton report:
              precision    recall  f1-score   support

           0       0.64      0.93      0.76      1485
           1       0.64      0.19      0.29       969

    accuracy                           0.64      2454
   macro avg       0.64      0.56      0.52      2454
weighted avg       0.64      0.64      0.57      2454

Ratio of false positives to false negatives:
0.13248407643312102


### Non-whites:

Confusion matrix:


array([[2385,  413],
       [1415,  547]])

Classificaton report:
              precision    recall  f1-score   support

           0       0.63      0.85      0.72      2798
           1       0.57      0.28      0.37      1962

    accuracy                           0.62      4760
   macro avg       0.60      0.57      0.55      4760
weighted avg       0.60      0.62      0.58      4760

Ratio of false positives to false negatives:
0.2918727915194346


### Enforcing Statistical Parity

In this part you will find the the group-specific thresholds for both models of judges' decision (with/without Yhat) that obtain statistical parity.

You can use a custom classifier `threshold` for the decision with this type of code snippet: `decisions = (logit.predict_proba(X) >= threshold).astype(int)`.

#### Model without Yhat

In [32]:
D_proba

0         1
0     0.632916  0.367084
1     0.615072  0.384928
2     0.531688  0.468312
3     0.558269  0.441731
4     0.578280  0.421720
...        ...       ...
7209  0.604953  0.395047
7210  0.609397  0.390603
7211  0.615436  0.384564
7212  0.704034  0.295966
7213  0.634510  0.365490

[7214 rows x 2 columns]

In [38]:
D_proba[1]

0       0.367084
1       0.384928
2       0.468312
3       0.441731
4       0.421720
          ...   
7209    0.395047
7210    0.390603
7211    0.384564
7212    0.295966
7213    0.365490
Name: 1, Length: 7214, dtype: float64

In [46]:
##Find the largest and lowest thresholds to enforce statistical parity
##hint: build a recursive function to find the probability threshold that minimizes 
## the difference between the predicted outcomes for whites and non whites
from scipy.optimize import minimize
threshold, diff = 0, 1

logistic = lambda x: 1/(1+np.exp(-x))
def difference(df, threshold):
    return (df[NW==1] >= logistic(threshold[0])).astype(int).mean() - (df[NW==0] >= logistic(threshold[1])).astype(int).mean()

def find_thresholds(df, threshold):
    return minimize(lambda x: difference(df, x), threshold, method='Nelder-Mead', options={'disp': True})

find_thresholds(D_proba_with[1], [0,0])


Optimization terminated successfully.
         Current function value: 0.083914
         Iterations: 6
         Function evaluations: 16


 final_simplex: (array([[ 0.00025   , -0.00025   ],
       [ 0.0001875 , -0.00025   ],
       [ 0.00023437, -0.00028125]]), array([0.08391376, 0.08391376, 0.08391376]))
           fun: 0.0839137611034634
       message: 'Optimization terminated successfully.'
          nfev: 16
           nit: 6
        status: 0
       success: True
             x: array([ 0.00025, -0.00025])

In [48]:
[logistic(x) for x in [0.00025, -0.00025]]

[0.5000624999996744, 0.4999375000003255]

#### Model with Yhat

In [49]:
find_thresholds(D_proba[1], [0,0])

Optimization terminated successfully.
         Current function value: 0.092828
         Iterations: 5
         Function evaluations: 14


 final_simplex: (array([[ 2.5000e-04,  0.0000e+00],
       [ 2.5000e-04, -6.2500e-05],
       [ 2.8125e-04, -4.6875e-05]]), array([0.09282804, 0.09282804, 0.09282804]))
           fun: 0.09282803585982072
       message: 'Optimization terminated successfully.'
          nfev: 14
           nit: 5
        status: 0
       success: True
             x: array([0.00025, 0.     ])

In [50]:
[logistic(x) for x in [0.00025, 0.     ]]

[0.5000624999996744, 0.5]

# Bonus 1: More Fairness Constraints

Find the threshold for both models (with/without Yhat) that obtains error rate balance (equality of recalls for each class.

In [21]:
##TODO

Find the threshold for both models (with/without Yhat) that obtains predictive parity (equality of precisions for each class).

In [22]:
##TODO

Find the threshold for both models (with/without Yhat) that obtains treatment equality (ratio of false positives to false negatives).

In [23]:
##TODO

# Bonus 2: Pre-Processing for Fairness

Regress all predictors in `X` on the protected attribute `A` and produce residuals `Xtilde`. Re-do the prediction task above (predicting judges' decision) and discuss how it changes the fairness metrics.

In [24]:
##TODO